del output\*.d
del output\*.crf
del output\*.__i
del output\*.lst
del output\*.htm
del output\*.dep
del output\*.lnp
del output\*.map
del output\*.axf
del output\*.bak
del output\*.o
deltree RTE
del *.bak
del *.uvguix.*
del jlinklog.txt
del *.dep
del *.scvd
del *.bin